// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionLink: typeof import('./src/components/ActionLink.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/forms/Button.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsCalendarAddOn: typeof import('~icons/material-symbols/calendar-add-on')['default']
    IMaterialSymbolsChevronRight: typeof import('~icons/material-symbols/chevron-right')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsDelete: typeof import('~icons/material-symbols/delete')['default']
    IMaterialSymbolsError: typeof import('~icons/material-symbols/error')['default']
    IMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    Input: typeof import('./src/components/forms/Input.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    ModuleList: typeof import('./src/components/ModuleList.vue')['default']
    ModuleMenu: typeof import('./src/components/ModuleMenu.vue')['default']
    ModulePicker: typeof import('./src/components/ModulePicker.vue')['default']
    Radio: typeof import('./src/components/forms/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/forms/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleGroupTransition: typeof import('./src/components/utils/ScaleGroupTransition.vue')['default']
    ScaleTransition: typeof import('./src/components/utils/ScaleTransition.vue')['default']
    Semester: typeof import('./src/components/Semester.vue')['default']
    SlideTransition: typeof import('./src/components/utils/SlideTransition.vue')['default']
  }
}
