// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsCalendarAddOn: typeof import('~icons/material-symbols/calendar-add-on')['default']
    IMaterialSymbolsDelete: typeof import('~icons/material-symbols/delete')['default']
    IMaterialSymbolsError: typeof import('~icons/material-symbols/error')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    ModuleList: typeof import('./src/components/ModuleList.vue')['default']
    ModuleMenu: typeof import('./src/components/ModuleMenu.vue')['default']
    ModulePicker: typeof import('./src/components/ModulePicker.vue')['default']
    Planner: typeof import('./src/components/Planner.vue')['default']
    ScaleGroupTransition: typeof import('./src/components/ScaleGroupTransition.vue')['default']
    ScaleTransition: typeof import('./src/components/ScaleTransition.vue')['default']
    Semester: typeof import('./src/components/Semester.vue')['default']
  }
}
