// Generated by ts-to-zod
import { z } from 'zod';

export const moduleTagSchema = z.object({
  name: z.string(),
  id: z.string(),
  checks: z.object({
    minEcts: z.number().optional(),
    maxEcts: z.number().optional()
  })
});

export const courseSchema = z.object({
  name: z.string(),
  type: z.string(),
  university: z.string()
});

export const turnusSchema = z.union([z.literal('WS'), z.literal('SS')]);

export const majorSchema = z.object({
  name: z.string(),
  type: z.string(),
  standardPeriod: z.number(),
  slug: z.string()
});

export const moduleSchema = z.object({
  name: z.string(),
  id: z.string(),
  ects: z.number(),
  rota: z.array(turnusSchema),
  description: z.string(),
  url: z.string(),
  tags: z.array(z.string()),
  semester: z.union([z.number(), z.undefined()])
});

export const semesterSchema = z.object({
  no: z.number(),
  modules: z.array(moduleSchema),
  turnus: turnusSchema,
  collectedEcts: z.number()
});

export const universitySchema = z.object({
  name: z.string(),
  otherNames: z.array(z.string()),
  slug: z.string(),
  majors: z.array(majorSchema)
});

export const plannerStoreSchema = z.object({
  version: z.string(),
  isSetup: z.boolean(),
  settings: z.object({
    start: turnusSchema
  }),
  modules: z.array(moduleSchema),
  tags: z.array(moduleTagSchema),
  semesterCount: z.number()
});
